language: java
jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.cache/pip
    - $HOME/.android-sdk # this may not be the best idea...
before_install:
  - pip install --user codecov
install:
  - ./gradlew core:assemble
script:
  - ./gradlew core:check
after_success:
  - codecov
# desktop:check has a broken test - should be included, but I want to see a passing build
# android:check needs an installed SDK, which could get complicated. We'll see
