language: java
jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - ./gradlew core:assemble
script:
  - ./gradlew core:check
# desktop:check has a broken test - should be included, but I want to see a passing build
# android:check needs an installed SDK, which could get complicated. We'll see
