language: java
jdk: oraclejdk8

env:
  - ANDROID_HOME="$HOME/.android"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/
#    - $HOME/.android-sdk # this may not be the best idea... - breaks the build, why?

addons:
  apt:
    packages:
    - libstdc++6:i386
    - lib32z1
    - expect